version: "3"

services:
  server:
    build: server/

    command: python3 server/server.py

    
    ports:
      - 5000:5000

  client:
    build: client/

    command: python3 client/client.py

    depends_on:
      - server
