version: "3"

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: ubuntu
    command: python3 server/server.py
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ubuntu
    command: python3 client/client.py
    depends_on:
      - server
