version: "3"

services:
  headnode:
    build: headnode/

    command: python3 headnode/headnode.py

  datanode1:
    build: datanode1/

    command: python3 datanode1/datanode1.py
    depends_on:
      - headnode

  datanode2:
    build: datanode2/

    command: python3 datanode2/datanode2.py
    depends_on:
      - headnode

  datanode3:
    build: datanode3/

    command: python3 datanode3/datanode3.py
    depends_on:
      - headnode
    
  client:
    build: client/

    command: python3 client/client.py

    depends_on:
      - headnode
